[versions]
kotlin = "2.3.21"
kotlinx-coroutines = "1.10.2"
springboot = "4.1.0"
springcloud = "2025.1.2"
#spring-statemachine = "4.0.1"
slf4j = "2.0.18"
jackson3 = "3.1.4"
lombok = "1.18.46"
drift = "1.24"
flink = "1.18.0"
storm = "2.6.1"

[libraries]
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect" }
kotlin-test-junit5 = { module = "org.jetbrains.kotlin:kotlin-test-junit5" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core" }
kotlinx-coroutines-reactor = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-reactor" }
kotlinx-serialization-protobuf = { module = "org.jetbrains.kotlinx:kotlinx-serialization-protobuf" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json" }

reactor-kotlin-extensions = { module = "io.projectreactor.kotlin:reactor-kotlin-extensions" }
reactor-test = { module = "io.projectreactor:reactor-test" }

springboot-bom = { module = "org.springframework.boot:spring-boot-dependencies", version.ref = "springboot" }
springboot-base = { module = "org.springframework.boot:spring-boot-starter" }
springboot-validation = { module = "org.springframework.boot:spring-boot-starter-validation" }
springboot-web = { module = "org.springframework.boot:spring-boot-starter-web" }
springboot-webflux = { module = "org.springframework.boot:spring-boot-starter-webflux" }
springboot-websocket = { module = "org.springframework.boot:spring-boot-starter-websocket" }
springboot-actuator = { module = "org.springframework.boot:spring-boot-starter-actuator" }
springboot-jpa = { module = "org.springframework.boot:spring-boot-starter-data-jpa" }
springboot-security = { module = "org.springframework.boot:spring-boot-starter-security" }
springboot-es = { module = "org.springframework.boot:spring-boot-starter-data-elasticsearch" }
springboot-auth-server = { module = "org.springframework.boot:spring-boot-starter-oauth2-authorization-server" }

springboot-test = { module = "org.springframework.boot:spring-boot-starter-test" }

springboot-web-test = { module = "org.springframework.boot:spring-boot-starter-webmvc-test" }
springboot-security-test = { module = "org.springframework.boot:spring-boot-starter-security-test" }
springboot-jpa-test = { module = "org.springframework.boot:spring-boot-starter-data-jpa-test" }

springcloud-bom = { module = "org.springframework.cloud:spring-cloud-dependencies", version.ref = "springcloud" }

#spring-statemachine-starter = { module = "org.springframework.statemachine:spring-statemachine-starter", version.ref = "spring-statemachine" }

jackson-databind = { module = "tools.jackson.core:jackson-databind" }
jackson-module-kotlin = { module = "tools.jackson.module:jackson-module-kotlin" }

guava = { module = "com.google.guava:guava", version = "33.5.0-jre" }
gson = { module = "com.google.code.gson:gson", version = "2.13.2" }

thrift-lib = { module = "org.apache.thrift:libthrift", version = "0.22.0" }

drift-client = { module = "io.airlift.drift:drift-client", version.ref = "drift" }
drift-server = { module = "io.airlift.drift:drift-server", version.ref = "drift" }
drift-transport-netty = { module = "io.airlift.drift:drift-transport-netty", version.ref = "drift" }

flink-clients = { module = "org.apache.flink:flink-clients", version.ref = "flink" }
flink-streaming-java = { module = "org.apache.flink:flink-streaming-java", version.ref = "flink" }
flink-table-api-java = { module = "org.apache.flink:flink-table-api-java", version.ref = "flink" }
flink-table-api-bridge-java = { module = "org.apache.flink:flink-table-api-java-bridge", version.ref = "flink" }

storm-client = { module = 'org.apache.storm:storm-client', version.ref = 'storm' }

slf4j-simple = { module = "org.slf4j:slf4j-simple", version.ref = "slf4j" }
lombok = { module = "org.projectlombok:lombok", version.ref = "lombok" }

postgres-driver = "org.postgresql:postgresql:42.7.8"
h2 = "com.h2database:h2:2.4.240"

[bundles]
flink = ["flink-clients", "flink-streaming-java", "flink-table-api-java", "flink-table-api-bridge-java"]
drift = ["drift-client", "drift-server", "drift-transport-netty"]
kt-springboot-test = ["kotlin-test-junit5", "springboot-test"]

kt-springboot-webflux = ["kotlin-reflect", "kotlinx-coroutines-reactor", "springboot-webflux", "reactor-kotlin-extensions", "jackson-module-kotlin"]

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm" }
kotlin-plugin-spring = { id = "org.jetbrains.kotlin.plugin.spring" }
kotlin-plugin-jpa = { id = "org.jetbrains.kotlin.plugin.jpa" }
kotlin-plugin-allopen = { id = "org.jetbrains.kotlin.plugin.allopen" }
springboot = { id = "org.springframework.boot" }

